### ISSUE TITLE
Task 1: Setting up Environment

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/BFS_51#1]
Learning about nodejs 
installing nodejs
running a node code

**Comment by cbohra** [comment]
![Image](https://github.com/yogeshtakeo/BFS_51/assets/166412548/0deb58e4-3719-49e6-9fea-c75de41ad3c8)

**Comment by samsub1111** [comment]
![Image](https://github.com/yogeshtakeo/BFS_51/assets/117606156/4f5a03b3-aad8-48c1-8cbb-dfe3abe2ad00)

**Comment by tarunChand28298** [comment]
![Image](https://github.com/yogeshtakeo/BFS_51/assets/44527962/e8fa992e-80d0-411e-ab27-5fd41cac4399)

**Comment by cbohra** [comment]
https://golden-mandazi-bff4fd.netlify.app/

**Comment by tarunChand28298** [comment]
https://takeo-react-exercise.vercel.app/

**Comment by Dinishan1997** [comment]
![Image](https://github.com/yogeshtakeo/BFS_51/assets/166424184/40a32bf5-0177-4a58-8128-1e97760f09a2)
