### ISSUE TITLE
Task 2: Vite Application

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/BFS_51#2]
We are going to create a vite application and we are going to serve it in the production as well.
while we learn React application we are going to see how we can manage our project.

**Comment by cbohra** [comment]
![Image](https://github.com/yogeshtakeo/BFS_51/assets/166412548/3c097b9f-72c4-4a8e-b4f1-2b50e0ef8f91)

**Comment by tarunChand28298** [comment]
https://takeo-react-exercise.vercel.app/
