### ISSUE TITLE
Task 3: HTML Semantics

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/BFS_51#3]
# **Task 3: HTML Semantics and CSS Styling in React JSX**
## **Objective:**
 Apply HTML semantics and CSS styling in a React JSX component.

## Task Overview

- Understand the importance of HTML semantics in web development.
- Implement HTML semantics in a React JSX component.
- Apply CSS styling to the React component using inline styles.

## Task Details

Read an article about the importance of HTML semantics in web development.
[HTML Semantics Link ](https://developer.mozilla.org/en-US/docs/Glossary/Semantics)

### Create a new React component:

- Open your existing React project or create a new one.

### Implement HTML semantics:

1. Inside the App.js, use HTML semantics to structure the content.
2. Add semantic HTML tags such as` <header>, <nav>, <main>, <section>, <article>, <aside>, and <footer>` to represent different sections of the component's content.
3. Place some placeholder content within each semantic tag (e.g., headings, paragraphs, and lists).
4. Apply CSS styling with inline styles:

Use inline styles in React JSX to apply CSS styling to the semantic components.
Select some of the semantic tags you added in the previous step and apply custom CSS styles using the style attribute in the JSX.
Experiment with different CSS properties such as background-color, color, font-size, padding, margin, and border.

### Render the Semantic components:

1. Import and render the Semantic component in another component
2. Verify that the Semantic components are rendered correctly and the CSS styles are applied through the inspect panel.

### Test and refine the styling:

- Open your project in a web browser and inspect the rendered semantic components.
- Adjust the CSS styles and properties as needed to achieve the desired visual appearance.
- Refresh the browser to see the updated styles.

## Task Submission
Take a screenshot of the rendered semantic components in the browser.
Share the screenshot of the output and the code that you have written in the issue comment box.
Don't forget to mention GitHub URL and your name in the comment section.

**Comment by tarunChand28298** [comment]
![output](https://github.com/yogeshtakeo/BFS_51/assets/44527962/38e07fa6-7337-4c32-9202-ffc1c5b0f2ad)

**Comment by samsub1111** [comment]
![Image](https://github.com/yogeshtakeo/BFS_51/assets/117606156/22771b45-441b-40b7-9ac2-4b7c6ae32d34)

**Comment by manojsingh49** [comment]
![html](https://github.com/yogeshtakeo/BFS_51/assets/166423904/9b14c431-bcb4-41d6-b785-0533db1119ad)

**Comment by cbohra** [comment]
![Image](https://github.com/yogeshtakeo/BFS_51/assets/166412548/a3ef5bba-9fc9-4477-8dba-c421d2d17025)

**Comment by cbohra** [comment]
![image](https://github.com/yogeshtakeo/BFS_51/assets/166412548/42ba38ae-5915-4753-86af-567d3e201d15)

**Comment by tarunChand28298** [comment]
![output](https://github.com/yogeshtakeo/BFS_51/assets/44527962/6ef05696-29a5-47f4-887e-31cb18a2ea74)

**Comment by manojsingh49** [comment]
![image](https://github.com/yogeshtakeo/BFS_51/assets/166423904/3bd4f2b2-4887-4a91-af0f-be68d916d357)
![image](https://github.com/yogeshtakeo/BFS_51/assets/166423904/89010900-d894-43c1-bdc7-96a805647790)
![image](https://github.com/yogeshtakeo/BFS_51/assets/166423904/73ee2069-bec1-4dd1-81d8-5e9832ed0f2d)

**Comment by cbohra** [comment]
![image](https://github.com/yogeshtakeo/BFS_51/assets/166412548/89bf008e-76f7-4c83-a781-dc3ddb80718a)

**Comment by AnanMoktan** [comment]
![Screenshot 2024-05-22 145944](https://github.com/yogeshtakeo/BFS_51/assets/89403086/f0b0c6f9-d6c1-44e9-88c9-9563ee8e1d6a)
https://master--idyllic-kitsune-500369.netlify.app/

GitHub username : AnanMoktan
GitHub link https://github.com/AnanMoktan/BFS_51/tree/c62c2db922a81b806f2af7c034b1926171550718
